[package]
name = "garner"
version = "0.1.0"
authors = ["Theo Lepage <theo.lepage@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.3"
nanoid = "0.3.0"